version: "3.4"
services:
 vite_docker:
   image: node:20.4
   container_name: vite_docker
   command: "yarn preview"
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
